
package group.ten.p2.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationBooking", targetNamespace = "http://soap.p2.ten.group/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ReservationBooking {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.p2.ten.group/ReservationBooking/bookSeatRequest", output = "http://soap.p2.ten.group/ReservationBooking/bookSeatResponse")
    public String bookSeat(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        int arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.p2.ten.group/ReservationBooking/getFlightsRequest", output = "http://soap.p2.ten.group/ReservationBooking/getFlightsResponse")
    public String getFlights();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.p2.ten.group/ReservationBooking/getSeatsRequest", output = "http://soap.p2.ten.group/ReservationBooking/getSeatsResponse")
    public String getSeats(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.p2.ten.group/ReservationBooking/helloWorldRequest", output = "http://soap.p2.ten.group/ReservationBooking/helloWorldResponse")
    public String helloWorld(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.p2.ten.group/ReservationBooking/getFlightRequest", output = "http://soap.p2.ten.group/ReservationBooking/getFlightResponse")
    public String getFlight(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
