
package group.ten.p2.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationBookingImplService", targetNamespace = "http://soap.p2.ten.group/", wsdlLocation = "http://localhost:8090/bookingservice?wsdl")
public class ReservationBookingImplService
    extends Service
{

    private final static URL RESERVATIONBOOKINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONBOOKINGIMPLSERVICE_EXCEPTION;
    private final static QName RESERVATIONBOOKINGIMPLSERVICE_QNAME = new QName("http://soap.p2.ten.group/", "ReservationBookingImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/bookingservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONBOOKINGIMPLSERVICE_WSDL_LOCATION = url;
        RESERVATIONBOOKINGIMPLSERVICE_EXCEPTION = e;
    }

    public ReservationBookingImplService() {
        super(__getWsdlLocation(), RESERVATIONBOOKINGIMPLSERVICE_QNAME);
    }

    public ReservationBookingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONBOOKINGIMPLSERVICE_QNAME, features);
    }

    public ReservationBookingImplService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONBOOKINGIMPLSERVICE_QNAME);
    }

    public ReservationBookingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONBOOKINGIMPLSERVICE_QNAME, features);
    }

    public ReservationBookingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationBookingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationBooking
     */
    @WebEndpoint(name = "ReservationBookingImplPort")
    public ReservationBooking getReservationBookingImplPort() {
        return super.getPort(new QName("http://soap.p2.ten.group/", "ReservationBookingImplPort"), ReservationBooking.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationBooking
     */
    @WebEndpoint(name = "ReservationBookingImplPort")
    public ReservationBooking getReservationBookingImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.p2.ten.group/", "ReservationBookingImplPort"), ReservationBooking.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONBOOKINGIMPLSERVICE_EXCEPTION!= null) {
            throw RESERVATIONBOOKINGIMPLSERVICE_EXCEPTION;
        }
        return RESERVATIONBOOKINGIMPLSERVICE_WSDL_LOCATION;
    }

}
